IMAGE_HEIGHT = 150
IMAGE_WIDTH = IMAGE_HEIGHT
CLASSES = 8
BATCH_SIZE = 16
EPOCHS = 100
AUGMENTATION = False

THREADS = 8

DATA_PATH = "/path/to/data/dir/"

TRAIN_SET_PATH = ""
VALID_SET_PATH = ""
TEST_SET_PATH = ""
SAVE_MODEL_PATH = ""